import fs from "fs/promises";
import path from "path";
import ora from "ora";
import chalk from "chalk";
import pkg from "@prisma/internals";
const { getDMMF } = pkg;

export async function generateCommand(options: { schema: string; out: string }): Promise<void> {
  const schemaPath = path.resolve(process.cwd(), options.schema);
  const outPath = path.resolve(process.cwd(), options.out);

  const spinner = ora("Generating validation schemas...").start();

  try {
    const schemaContent = await fs.readFile(schemaPath, "utf-8");

    // Parse the Prisma schema into an AST (DMMF)
    spinner.text = `Parsing Prisma schema from ${chalk.cyan(options.schema)}...`;
    const dmmf = await getDMMF({ datamodel: schemaContent });

    spinner.text = `Generating Zod schemas to ${chalk.cyan(options.out)}...`;
    const generatedCode = generateZodCode(dmmf);

    // Create output directory if it doesn't exist
    await fs.mkdir(path.dirname(outPath), { recursive: true });
    
    // Write generated code
    await fs.writeFile(outPath, generatedCode, "utf-8");

    spinner.succeed(`Generated ZerithDB schemas to ${chalk.cyan(options.out)}`);
  } catch (err: any) {
    spinner.fail("Schema generation failed");
    console.error(chalk.red(`Error: ${err.message}`));
    process.exit(1);
  }
}

function generateZodCode(dmmf: any): string {
  let code = `// AUTO-GENERATED BY ZERITHDB CLI
// DO NOT MODIFY THIS FILE DIRECTLY

import { z } from "zod";

`;

  // Process each model in the Prisma schema
  for (const model of dmmf.datamodel.models) {
    const modelName = model.name;
    let fieldsCode = "";

    for (const field of model.fields) {
      // Map Prisma types to Zod types
      let zodType = "z.any()";
      
      switch (field.type) {
        case "String":
          zodType = "z.string()";
          break;
        case "Int":
        case "Float":
        case "Decimal":
          zodType = "z.number()";
          break;
        case "Boolean":
          zodType = "z.boolean()";
          break;
        case "DateTime":
          zodType = "z.date()";
          break;
        case "Json":
          zodType = "z.any()";
          break;
      }

      if (field.isList) {
        zodType = `z.array(${zodType})`;
      }

      if (!field.isRequired && !field.isId && !field.hasDefaultValue) {
         zodType = `${zodType}.optional()`;
      }
      if (field.kind === "object") {
        continue; 
      }

      fieldsCode += `  ${field.name}: ${zodType},\n`;
    }

    code += `export const ${modelName}Schema = z.object({\n${fieldsCode}});\n\n`;
    code += `export type ${modelName} = z.infer<typeof ${modelName}Schema>;\n\n`;
  }

  return code;
}
